// Code generated by MockGen. DO NOT EDIT.
// Source: ml.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gocv "gocv.io/x/gocv"
)

// MockNeuralNet is a mock of NeuralNet interface
type MockNeuralNet struct {
	ctrl     *gomock.Controller
	recorder *MockNeuralNetMockRecorder
}

// MockNeuralNetMockRecorder is the mock recorder for MockNeuralNet
type MockNeuralNetMockRecorder struct {
	mock *MockNeuralNet
}

// NewMockNeuralNet creates a new mock instance
func NewMockNeuralNet(ctrl *gomock.Controller) *MockNeuralNet {
	mock := &MockNeuralNet{ctrl: ctrl}
	mock.recorder = &MockNeuralNetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNeuralNet) EXPECT() *MockNeuralNetMockRecorder {
	return m.recorder
}

// SetPreferableBackend mocks base method
func (m *MockNeuralNet) SetPreferableBackend(backend gocv.NetBackendType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPreferableBackend", backend)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPreferableBackend indicates an expected call of SetPreferableBackend
func (mr *MockNeuralNetMockRecorder) SetPreferableBackend(backend interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPreferableBackend", reflect.TypeOf((*MockNeuralNet)(nil).SetPreferableBackend), backend)
}

// SetPreferableTarget mocks base method
func (m *MockNeuralNet) SetPreferableTarget(target gocv.NetTargetType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPreferableTarget", target)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPreferableTarget indicates an expected call of SetPreferableTarget
func (mr *MockNeuralNetMockRecorder) SetPreferableTarget(target interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPreferableTarget", reflect.TypeOf((*MockNeuralNet)(nil).SetPreferableTarget), target)
}

// SetInput mocks base method
func (m *MockNeuralNet) SetInput(blob gocv.Mat, name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetInput", blob, name)
}

// SetInput indicates an expected call of SetInput
func (mr *MockNeuralNetMockRecorder) SetInput(blob, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInput", reflect.TypeOf((*MockNeuralNet)(nil).SetInput), blob, name)
}

// ForwardLayers mocks base method
func (m *MockNeuralNet) ForwardLayers(outBlobNames []string) []gocv.Mat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForwardLayers", outBlobNames)
	ret0, _ := ret[0].([]gocv.Mat)
	return ret0
}

// ForwardLayers indicates an expected call of ForwardLayers
func (mr *MockNeuralNetMockRecorder) ForwardLayers(outBlobNames interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForwardLayers", reflect.TypeOf((*MockNeuralNet)(nil).ForwardLayers), outBlobNames)
}

// Close mocks base method
func (m *MockNeuralNet) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockNeuralNetMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockNeuralNet)(nil).Close))
}
